=== jeszy75/xsd11-examples/openContent/1/document.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:import namespace="http://example/annotation" schemaLocation="annotation.xsd"/>

    <xs:element name="document">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="title" type="xs:string"/>
                <xs:element ref="section" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="section">
        <xs:complexType>
            <xs:openContent mode="interleave">
                <xs:any namespace="http://example/annotation" processContents="lax"/>
            </xs:openContent>
            <xs:sequence>
                <xs:element name="title" type="xs:string"/>
                <xs:element name="para" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="link" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="url" type="xs:anyURI" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== jeszy75/xsd11-examples/openContent/document.xml
<?xml version="1.0"?>
<document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:a="http://example/annotation"
    xsi:noNamespaceSchemaLocation="document.xsd">

    <title>The title of the document</title>

    <section>
        <title>Section 1</title>
        <para>Nulla eu venenatis dolor.Sed nibh felis, feugiat quis ornare sit amet, volutpat nec
            neque. Pellentesque semper, nibh id rhoncus tincidunt, risus risus pellentesque leo,
            facilisis iaculis ante nisl in ligula.</para>
        <para>Morbi rhoncus sapien id magna consectetur laoreet. Ut pellentesque fringilla
            ullamcorper.Curabitur posuere luctus nisl at commodo. Nulla sit amet tortor turpis, ut
            ornare lectus. Donec quam nulla, egestas quis pretium sed, accumsan lobortis nunc.
            Vestibulum tincidunt dapibus lectus, sed luctus purus imperdiet vitae.</para>
    </section>

    <section>
        <title>Section 2</title>
        <para>Nulla gravida blandit erat, eu viverra neque elementum a. Cras lacinia semper dapibus.
            In nec odio dignissim erat posuere iaculis vel ut leo. Sed eget ipsum metus. Vestibulum
            luctus est non neque placerat imperdiet.</para>
    </section>

</document>
