=== jeszy75/xsd11-examples/assert/4/bugs.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="bugs">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="bug" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="bug">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="submit-date" type="xs:dateTime"/>
                <xs:element name="description" type="xs:string"/>
                <xs:element name="close-date" type="xs:dateTime" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="status" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="open"/>
                        <xs:enumeration value="closed"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:assert test="if (@status = 'open') then not(close-date) else if (@status = 'closed') then close-date else false()"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== jeszy75/xsd11-examples/assert/4/bugs.xml
<?xml version="1.0"?>
<bugs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="bugs.xsd">

    <bug status="open">
        <submit-date>2012-09-03T13:15:00</submit-date>
        <description>Unable to set images as background</description>
    </bug>

    <bug status="closed">
        <submit-date>2012-09-11T14:43:00</submit-date>
        <description>The File dialog does not update when a new folder is created</description>
        <close-date>2012-09-28T00:03:00</close-date>
    </bug>

</bugs>
